- name: Get Index Page from Workshop Site
  uri:
    url: "{{ workshop_url }}"
    status_code: 200 
    return_content: yes
    validate_certs: no 
  register: workshop_index_html
  
# Yes.  This is exceptionally ugly...  and it works.
- name: Get Student Pod Info
  shell: grep -E '\bssh student[0-9]{1,2}@[0-9].*\b' | sed -E 's/.*student([0-9]{1,2})\@([0-9.]*).*$/\1 \2/'
  args:
    stdin: "{{ workshop_index_html.content }}"
  register: student_list

# Unfortunate... But it's one way to populate the info...
- name: Create student info variable
  set_fact:
     workshop_students: "{{ workshop_students|default([]) + [[ item.split(' ')[0]|int, item.split(' ')[1] ]] }}"
  with_items: "{{ student_list.stdout_lines }}"
  
- debug: msg={{ workshop_students }}

- name: Create template
  template:
    src: templates/rhdemo.ca.conf.j2
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/rhdemo.ca.conf
  notify: Restart HTTPD